name: Build, Test, Analyze, and Publish Packages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-test-analyze-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      # ---------------------
      # 🔹 CUSTOMER-APP
      # ---------------------
      - name: Install dependencies (customer-app)
        run: npm install
        working-directory: ./customer-app

      - name: Run tests (customer-app)
        run: npm run test:cov
        working-directory: ./customer-app

      - name: SonarCloud Scan (customer-app)
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          projectBaseDir: ./customer-app
          args: >
            -Dsonar.organization=proyectou
            -Dsonar.projectKey=proyectou_lab2nest
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish (customer-app)
        run: |
          npm run build
          npm version patch --no-git-tag-version
          npm pkg delete private || true
          npm pkg set name="@mayrafc/customer-app_chire"
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NUGET }}" > ~/.npmrc
          npm config set registry "https://npm.pkg.github.com/"
          npm publish --access public
        working-directory: ./customer-app

      # ---------------------
      # 🔹 NOTIFICATIONS
      # ---------------------
      - name: Install dependencies (notifications)
        run: npm install
        working-directory: ./notifications

      - name: Run tests (notifications)
        run: npm run test:cov
        working-directory: ./notifications

      - name: SonarCloud Scan (notifications)
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          projectBaseDir: ./notifications
          args: >
            -Dsonar.organization=proyectou
            -Dsonar.projectKey=proyectou_lab2nest
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish (notifications)
        run: |
          npm run build
          npm version patch --no-git-tag-version
          npm pkg delete private || true
          npm pkg set name="@mayrafc/notifications_chire"
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NUGET }}" > ~/.npmrc
          npm config set registry "https://npm.pkg.github.com/"
          npm publish --access public
        working-directory: ./notifications
