name: 📘 Publish Documentation (Both)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (customer-app)
        run: npm install
        working-directory: ./customer-app

      - name: 📦 Install dependencies (notifications)
        run: npm install
        working-directory: ./notifications

      - name: 🏗️ Generate docs (customer-app)
        run: npx @compodoc/compodoc -p tsconfig.json -d ../../documentation/customer-app --disableSourceCode
        working-directory: ./customer-app

      - name: 🏗️ Generate docs (notifications)
        run: npx @compodoc/compodoc -p tsconfig.json -d ../../documentation/notifications --disableSourceCode
        working-directory: ./notifications

      - name: 🚀 Deploy all docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
